name: Deployment

on:
  push:
    branches: [ "main" ]


jobs:

  build:

      name: Setup Gcloud Account
      runs-on: ubuntu-latest
      env:
          IMAGE_NAME: ${{ vars.GCP_ARTIFACT_URL }}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME_BACKEND }}/${{ vars.GCP_ARTIFACT_URL }}
      
      steps:

        - name: Checkout repository
          uses: actions/checkout@v2

        - id: 'auth'
          uses: google-github-actions/auth@v1
          with:
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v1'

        - name: 'Use gcloud CLI'
          run: 'gcloud info'

        - name: Configure Docker
          run: gcloud auth configure-docker

        - name: Build Docker image
          run: docker build . -t $IMAGE_NAME

        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Deploy Docker image
          run: gcloud run deploy ${{ secrets.GCP_APP_NAME_BACKEND }} --image $IMAGE_NAME --region southamerica-east1 --platform managed
